project:
  type: book
  resources: static/*
  output-dir: ../_docs
  # pre-render: 
  # post-render:
 
book:
  title: "ECHILD How To Guides"
  reader-mode: true
  page-footer: >
    The content of this site is licensed under the
    [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license](https://creativecommons.org/licenses/by-nc-sa/4.0/),
    except example source code which is provided under the
    [MIT license](https://github.com/UCL-ECHILD/howto.echild.ac.uk-website/blob/main/LICENSE.md).
  # cover-image: cover.jpg
  # favicon: favicon.ico
  site-url: https://howto.echild.ac.uk/
  repo-url: https://github.com/UCL-ECHILD/howto.echild.ac.uk-website
  repo-subdir: web_source/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - glossary.qmd
    - acknowledgements.qmd
    - part: "Guides"
      chapters:
        - guide01_intro.qmd
        - guide02_mgmt.qmd
        - guide03_cohort.qmd
        - guide04_demo_npd.qmd
        - guide05_demo_hes.qmd
        - guide06_birth_chars.qmd
        - guide07_phenotype.qmd
        - guide08_enr_abs_excl.qmd
        - guide09_exam.qmd
        - guide10_opa.qmd
        - guide11_combine.qmd
        - guide12_csc.qmd
format:
  html:
    theme:
      - cosmo
    code-copy: true
    code-link: true
    
# bibliography: references.bib
# csl: CITATION-STYLE.csl
# link-citations: true
# nocite: |
#   @*
